### ISSUE TITLE
Docker error "Couldn't load integration instances from config file"

### ISSUE THREAD

**Issue by arielsalvo** [newrelic/nri-haproxy#16]
Hi

I kept getting the following error when trying out docker image [newrelic/k8s-nri-haproxy:2.1.0](https://hub.docker.com/layers/newrelic/k8s-nri-haproxy/2.1.0/images/sha256-8c72d8bfbdb94f272773f4eeb876e183e74f020f3c3c28be84b12813b98f2288):
```
"Couldn't load integration instances from config file" component=PluginRegistry configFile=haproxy-config.yml error="Integration definition not found" integration=com.newrelic.haproxy
```

Had to import the definition to another directory for newrelic-infrastructure to pick it up: `/var/db/newrelic-infra/custom-integrations/haproxy-definition.yml`
This should be changed in:
https://github.com/newrelic/nri-haproxy/blob/10f84727b7dd6ed6185f9b9c893461470b2f12c8/Dockerfile#L11

Also, the path to the sidecar in the already included definition appears not to work unless changed from `./bin/nri-haproxy` to the absolute path `/nri-sidecar/newrelic-infra/newrelic-integrations/bin/nri-haproxy`

After these changed, it worked for me. Is there a better way to do this?

Thanks!
    --Ariel

**Comment by camdencheek** [comment]
Hi @arielsalvo -- The generally recommended way of doing this is to use a ConfigMap. It should look something like the following:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-newrelic-integrations-config
  namespace: default
data:
  config.yaml: |
    integration_name: com.newrelic.haproxy
    instances:
      - name: haproxy
        # Command can be all_data, metrics, or inventory
        command: all_data
        arguments:
          stats_url: http://127.0.0.1:7777/stats
          username: cacheuser
          password: password
          cluster_name: mmacias
  definition.yaml: |
    name: com.newrelic.haproxy
    description: Reports status and metrics for haproxy service
    protocol_version: 2
    os: linux
    commands:
      all_data:
        command:
          - ./bin/nr-haproxy
        prefix: config/haproxy
        interval: 15
      metrics:
        command:
          - ./bin/nr-haproxy
          - --metrics
        interval: 15
      inventory:
        command:
          - ./bin/nr-haproxy
          - --inventory
        prefix: config/haproxy
        interval: 15
```
